# Generated by Django 3.0 on 2019-12-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_image_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image', upload_to='images/'),
        ),
    ]
