# Generated by Django 3.0 on 2019-12-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20191216_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='category_item',
        ),
    ]
