# Generated by Django 3.0 on 2019-12-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20191216_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
