# Generated by Django 3.0 on 2019-12-16 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_remove_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(db_column='category', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='image.Category'),
            preserve_default=False,
        ),
    ]
