# Generated by Django 3.0 on 2019-12-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_auto_20191216_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
