# Generated by Django 3.0 on 2019-12-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0014_auto_20191216_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loc_name',
            new_name='location_name',
        ),
    ]
